### PR TITLE
Don't pad channel masses

### LINKED ISSUE #1: Barcode keys with channel 89 don't work
See http://cytoforum.stanford.edu/viewtopic.php?f=3&t=762&view=unread#unread
For some reason that channel isn't getting found in the FCS file header.

### PR DESCRIPTION
**Pull request by zbjornson**
num2str makes a right-aligned, space-padded vector by default

Fixes #1

### CODE REVIEW

**Comment by zbjornson** [comment]
@mleipold I don't suppose you have Matlab itself (not just the runtime), do you? This fixes the issue you raised on the forum, but I only have Matlab on Linux and can't compile it for MacOS or Windows right now.

**Comment by mleipold** [comment]
@zbjornson:  yes, I do have full Matlab R2014a.  

But if you want me to compile, you're going to have to lead me through how to do that.  :)

**Comment by zbjornson** [comment]
Awesome. These instructions should work 🤞

1. Download and extract https://github.com/nolanlab/single-cell-debarcoder/archive/cee92c3.zip
1. Make sure you have the [Gating-ML](https://www.mathworks.com/matlabcentral/fileexchange/46106-gating-ml?focused=3859268&tab=function) addon installed. If not, from within Matlab, click on the Apps tab, then "get add-ons" on the left, search for "gating-ml", click "add to Matlab".
1. Browse to the above folder in the sidebar in Matlab, then right click on `single_cell_debarcode_gui.m` and click "run".

Might have a colleague who can post a compiled version later today if you hit any snags and don't feel like troubleshooting.

**Comment by mleipold** [comment]
Hi Zach, 

As far as I can tell from my Apps list, I don't have Gating-ML.  I followed your link, but I don't see an "add to Matlab" option, all I see is a "Download" button.  It prompts me to download the file; I get a ZIP.  

However, after unzipping, I can't find a Matlab installer file as specified here:  
https://www.mathworks.com/videos/packaging-and-installing-matlab-apps-70404.html?s_tid=srchtitle

**Comment by zbjornson** [comment]
Hi Mike,

For the Gating-ML addon, if you use the "download" button in the link, then you need to use the "Install App" button here:

image

but alternatively, you can just click "get more apps" (sorry, I said "get add-ons" previously) and search for "gating-ml" there.

**Comment by mleipold** [comment]
If I hit "Get More Apps", it takes me to the Mathworks website, MATLAB apps.

If I search in "Explore Apps on Matlab file exchange" (blue button), I can't find Gating-ML (see screenshot).
If I explore in "Search Mathworks.com" (upper right), I can find it, but it leads me back to the Download button.

If I do the download button, I'm still stuck without the *.mlappinstall file for it.

search mathworkscom-result
get more apps-search mathworksdotcom
get more apps-explore apps on matlab file exchange

**Comment by mleipold** [comment]
no installer file

**Comment by zbjornson** [comment]
Ugh, stupid little trick: once you've hit "get more apps" and are in the search page there, hit backspace a few times in the search box to clear the "app" filter. Then you should be able to search for "gating-ml" hopefully.

(Colleague says he thinks he can compile this around 5 today if you don't want to spend time figuring this out.)

**Comment by mleipold** [comment]
OK, I found it in the App Exchange, but I still don't see an "Add to Matlab" button....I tried hovering over all the icons, and still didn't see anything like that.

gatingml found-noaddtomatlabbutton

It might be faster if you have your colleague do it....sorry.  Let me know if it doesn't work out somehow, and I'll try to go further tomorrow.

**Comment by tjburns08** [comment]
[MyAppInstaller_web.zip](https://github.com/nolanlab/single-cell-debarcoder/files/1143732/MyAppInstaller_web.zip)

**Comment by zbjornson** [comment]
Thanks Tyler!

@mleipold I think that should work on MacOS. Unzip it, then it should be a MacOS installer that just works, hopefully ...

**Comment by mleipold** [comment]
OK, I downloaded the zip, and installed it.  Was I supposed to get this message at the end?

mcr root

I have opened the application, it has me choose a CSV, and then it collapses without ever asking me to select an FCS file.

**Comment by zbjornson** [comment]
Urg, I'm not sure, sorry :(. I gotta find a MacOS machine to do this on so I can test it without continuing to send you on a wild goose chase... Lemme see what I can find in the next day or two.

**Comment by mleipold** [comment]
Thanks.  I'm happy to keep testing things, but I'm way out of my abilities in terms of altering code.

And I'm happy to be Beta1 when you get something you think is working.

**Comment by rfinck** [comment]
I have been out of the debarcoding loop for a while and also do not have Matlab. But, a couple thoughts:

Since no one is actively maintaining this other than @zbjornson's much-appreciated efforts, and since this issue exactly shows why Matlab is a problematic choice, I encourage you to check out https://github.com/parkerICI/premessa. I have not used it myself but believe it has the same or better functionality as this with the bonus of being implemented in friendly open-source R, plus having the regular attention of @pfgherardini. 

For now, if you want to keep trudging away here, a tip for @mleipold to resolve that message:

 First you need to figure out whether you already have an environment variable named DYLD_LIBRARY_PATH. To check this, open up your Terminal and type: 

```
echo $DYLD_LIBRARY_PATH
```

 If you get nothing back, then that variable is not defined and you can use the first option. To do this, you need to first find the directory where you've installed the MCR, such as `/Users/mleipold/Applications/MATLAB/MATLAB_Comiler_Runtime`. Then replace `MCR_ROOT` in the suggested command in the Terminal as follows (obviously you will need to adjust this for what your directory name actually is):

```
DYLD_LIBRARY_PATH=/Users/mleipold/Applications/MATLAB/MATLAB_Comiler_Runtime/v901/runtime/maci64:/Users/mleipold/Applications/MATLAB/MATLAB_Comiler_Runtime/v901/sys/os/maci64:/Users/mleipold/Applications/MATLAB/MATLAB_Comiler_Runtime/v901/bin/maci64
export DYLD_LIBRARY_PATH
```

If you get something path that shows your `DYLD_LIBRARY_PATH` is already defined, then prepend ${DYLD_LIBRARY_PATH}$ to that:

```
DYLD_LIBRARY_PATH=${DYLD_LIBRARY_PATH}:/Users/mleipold/Applications/MATLAB/MATLAB_Comiler_Runtime/v901/runtime/maci64:/Users/mleipold/Applications/MATLAB/MATLAB_Comiler_Runtime/v901/sys/os/maci64:/Users/mleipold/Applications/MATLAB/MATLAB_Comiler_Runtime/v901/bin/maci64
export DYLD_LIBRARY_PATH
```

Again my hands are pretty tied since I don't have Matlab, but I'll take another look over the weekend.

**Comment by pfgherardini** [comment]
Hi @mleipold! As Rachel mentioned i have been working on a re-implementation of normalization and de-barcoding in R which you can find here https://github.com/parkerICI/premessa

Feedback is very welcome. The software also includes a GUI for renaming and synchronizing FCS panels across a large number of files

**Pull request merged**
